[package]
name = "mrray-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auto_ops = "0.3.0"
rand = "0.8.5"

[profile.release]
strip = true
lto = 'thin'
